### ISSUE TITLE
Markdoc Tags appear to be incompatable with MUI components.

### ISSUE THREAD

**Issue by WatsonWBlair** [markdoc/markdoc#232] opened 2022-09-29 17:56 UTC
### What happened?

Starting from the Next.js starter repo, if you attempt to define a tag that utilizes Material UI components all custom tags fail to load. there are two issues here:

1. Markdoc Tags seem to be incompatible with MUI Components
2. Custom Tags do not fail gracefully, so an error in one custom tag causes all custom tags to fail.

Sorry if this issue is logged in the wrong place, but the [markdoc/next.js repo](https://github.com/markdoc/next.js) does not allow issue reports....

Thanks in advance!

### To reproduce

1. Clone down the [Markdoc-Starter repo](https://github.com/markdoc/markdoc-starter)
2. Install MUI according to the[ startup documentation](https://mui.com/material-ui/getting-started/installation/) (npm install @mui/material @emotion/react @emotion/styled)
3. Update `components/Callout.tsx` to use the MUI Card component:
```
import * as React from 'react';
import dynamic from 'next/dynamic'

const DynamicCard = dynamic(() => import('@mui/material/Card') , {
  suspense: true,
})

export function Callout({ title, children }) {
  return (
    <DynamicCard className='callout'>
      <strong>{title}</strong>
      <span>{children}</span>
      <style jsx>
        {`
          .callout {
            display: flex;
            flex-direction: column;
            padding: 12px 16px;
            background: #f6f9fc;
            border: 1px solid #dce6e9;
            border-radius: 4px;
          }
          .callout :global(p) {
            margin: 0;
          }
        `}
      </style>
    </DynamicCard>
  );
}

```
4. execute `npm run dev`
5. view `localhost:3000` in the browser
6. the following error is output to the console:
```
wait  - compiling / (client and server)...
Undefined tag: 'callout'
Can't nest 'image' in 'link'
Can't nest 'image' in 'link'
Error: Undefined tag: 'callout'
{% callout %}

    at Object.load (/Users/wbliar/Development/markdoc-starter/node_modules/@markdoc/next.js/src/loader.js:150:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.loader (/Users/wbliar/Development/markdoc-starter/node_modules/@markdoc/next.js/src/loader.js:297:20)
error - ./pages/index.md
```
Additionally, in contexts where multiple custom tags are defined all custom tags become undefined:
```
Undefined tag: 'authorizations'
Undefined tag: 'callout'
Undefined tag: 'chip'
Undefined tag: 'note'
Undefined tag: 'output'
Undefined tag: 'response'
Undefined tag: 'tabs'
Undefined tag: 'tab'
Undefined tag: 'example'
Error: Undefined tag: 'authorizations'
{% authorizations %} Some Auth {% /authorizations %}

Undefined tag: 'callout'
{% callout title="Callout Title" %} Callout Body {% /callout %}

Undefined tag: 'chip'
{% chip %} This is a chip{% /chip %}

Undefined tag: 'note'
{% note type="note type" %} this one is a note {% /note %}

Undefined tag: 'output'
{% output label="label" value="value" /%}

Undefined tag: 'response'
{% response code="200" description="Response Description" %}this is a response{% /response %}

Undefined tag: 'tabs'
{% tabs title="tabs title" %}

Undefined tag: 'tab'
{% tab label="tab label" %}

Undefined tag: 'example'
{% example type="example type" label="example label" %} Way down here with an example my dude {% /example %}

    at Object.load (/Users/wbliar/Development/doc/node_modules/@markdoc/next.js/src/loader.js:150:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.loader (/Users/wbliar/Development/doc/node_modules/@markdoc/next.js/src/loader.js:297:20)
error - ./pages/tags.md
```

### Version

 "@markdoc/markdoc": "^0.1.11",

### Additional context

    "@markdoc/markdoc": "^0.1.11",
    "@markdoc/next.js": "^0.1.8",
    "@mui/material": "^5.10.7",
    "next": "^12.3.1",

**Comment by mfix-stripe** [comment] 2022-09-29 18:05
Looks like this is a duplicate of #231. Will track this issue over there. Thanks!

**Closed by mfix-stripe** 2022-09-29 18:05 UTC
Labels: bug
