### ISSUE TITLE
Markdoc Next plugin bundles entire Markdoc library

### ISSUE THREAD

**Issue by davidsainez** [markdoc/markdoc#332] opened 2023-02-20 11:16 UTC
First, thanks for this awesome tool!

I've set up Markdoc according to the next starter and the plugin ships the entire Markdoc library. Given that it weighs ~45KB (gzipped), it can noticeably decrease page load times.

It should be enough to only ship the render code.

**Comment by mfix-stripe** [comment] 2023-02-22 18:48
@de-varela, can you share more about how you have determined this? Next.js should code-split this automatically, and we have previously used https://next-code-elimination.vercel.app/ to confirm this, but maybe there is a regression.

(Cc @rpaul-stripe for vis)

**Comment by bholmesdev** [comment] 2023-03-03 16:59
So correct me if I'm wrong, but I'm not sure you _can_ code split anything from the Markdoc package. It seems, when using the `serverSideProps` option, everything from Markdoc's parse to the render stage is shipped to the server runtime with all associated dependencies.

This motivated a hybrid approach in the [Astro team's experimental integration](https://github.com/withastro/roadmap/pull/508/files#diff-657d5ed415c80a491ecf474d170bd5c8900b5edfe4b0d16b8c5a3fe02a9bc522R108-R112), where we perform the parse and transform phases at build time to validate your Markdoc ahead-of-time and only ship rendering to the SSR runtime. Curious if I'm missing optimizations there though!

**Comment by mfix-stripe** [comment] 2023-03-03 17:32
@bholmesdev the Next.js plugin supports 2 options, `static` or `server`, which map to `getStaticProps` and `getServerSideProps`. 

`getStaticProps` gets called at build time, in which case this _should_ line up with your approach—we will ship the minimal JSON bundle. 

The `server` option allows users to opt-in to a server-side rendering approach, in which case the markdoc library will be included in lambdas, but only Markdoc's react-renderer will get shipped to the frontend.

**Comment by mfix-stripe** [comment] 2023-06-02 20:37
Going to close this since the entire Markdoc library shouldn't be bundled according to https://next-code-elimination.vercel.app.

@davidsainez if you can share a reproduction of this bug, I will reopen this issue and fix it 👍

**Closed by mfix-stripe** 2023-06-02 20:37 UTC
Labels: next.js
