### ISSUE TITLE
Unclosed selfClosing tag vacuums everything after it in the page

### ISSUE THREAD

**Issue by RomanHotsiy** [markdoc/markdoc#476] opened 2024-01-05 06:45 UTC
### What happened?

It would be great if self-closing tag parsing assumes the tag is meant to be closed and doesn't parse all of the following content as children.

### To reproduce

It is reproducible [in the sanbox](https://markdoc.dev/sandbox?mode=preview&c=LS0tCnRpdGxlOiBXaGF0IGlzIE1hcmtkb2M%252FCi0tLQoKIyB7JSAkbWFya2RvYy5mcm9udG1hdHRlci50aXRsZSAlfSB7JSAjb3ZlcnZpZXcgJX0KCk1hcmtkb2MgaXMgYSBNYXJrZG93bi1iYXNlZCBzeW50YXggYW5kIHRvb2xjaGFpbiBmb3IgY3JlYXRpbmcgY3VzdG9tIGRvY3VtZW50YXRpb24gc2l0ZXMuIFN0cmlwZSBjcmVhdGVkIE1hcmtkb2MgdG8gcG93ZXIgW291ciBwdWJsaWMgZG9jc10oaHR0cDovL3N0cmlwZS5jb20vZG9jcykuCgp7JSBjYWxsb3V0IHR5cGU9ImNoZWNrIiAlfQpNYXJrZG9jIGlzIG9wZW4tc291cmNl4oCUY2hlY2sgb3V0IGl0cyBbc291cmNlXShodHRwOi8vZ2l0aHViLmNvbS9tYXJrZG9jL21hcmtkb2MpIHRvIHNlZSBob3cgaXQgd29ya3MuCnslIC9jYWxsb3V0ICV9CgojIyBIb3cgaXMgTWFya2RvYyBkaWZmZXJlbnQ%252FCgp7JSBwYXJ0aWFsIHByaW1hcnk9InBlbmNpbCIgJX0KCk1hcmtkb2MgdXNlcyBhIGZ1bGx5IGRlY2xhcmF0aXZlIGFwcHJvYWNoIHRvIGNvbXBvc2l0aW9uIGFuZCBmbG93IGNvbnRyb2wsIHdoZXJlIG90aGVyIHNvbHV0aW9uc%252BKApiBbUmVhZCBtb3JlXSgvZG9jcy9vdmVydmlldykuCgojIyBOZXh0IHN0ZXBzCi0gW0luc3RhbGwgTWFya2RvY10oL2RvY3MvZ2V0dGluZy1zdGFydGVkKQotIFtFeHBsb3JlIHRoZSBzeW50YXhdKC9kb2NzL3N5bnRheCkK)

**Comment by rpaul-stripe** [comment] 2024-01-08 16:34
This is as designed — a self-closing tag needs to have a forward slash (similar to XML) in order to explicitly indicate that it is self-closing: `{% partial file="" /%}`. Without the slash, the parser assumes that it is an opening tag, so nesting the subsequent content as children is expected behavior.

The parser itself does not have access to the schema and does not know which tags are supposed to be self-closing. Parsing behavior in Markdoc is deterministic and based solely on the syntax, so self-closing tags need to be syntactically distinct from opening tags.

**Closed by rpaul-stripe** 2024-01-08 16:34 UTC
Labels: bug

**Comment by mDuo13** [comment] 2024-01-09 21:38
I just want to chime in to say I'm disappointed in this resolution.

At a minimum, the error handling should be better, to identify and report the syntax error. But, realistically, it feels like a huge missed opportunity to have a schema where you define which tags are self-closing and which aren't if you don't actually use that data to inform parsing. 

I'm old enough to remember the failed attempt to migrate the web to XHTML, which failed because, realistically, people make flawed documents and an HTML parser that produces what they probably wanted most of the time is more desirable than a parser that throws up its hands in failure at the slightest imperfection. The type of authors you should expect to be writing Markdoc are, I would expect, on average even less technically-minded than web developers, so it makes sense to me that you would want the parser to be as forgiving as HTML. Ordinary Markdown, for all its quirks, is generally pretty forgiving and intuitive, so pitfalls like this are a big step away from what made it catch on.

The problem is pretty obvious if it occurs at the beginning of a page, but it can be a lot more mysterious if you have one unclosed tag 3/4 of the way through a multi-page document with a bunch of stuff. To make matters worse, [the syntax for _variables_](https://markdoc.dev/docs/variables) looks exactly like an unclosed tag, which makes it even easier to make these mistakes by accident and harder to spot them after the fact.

Ultimately it's not my project so you can do things how you like, but perhaps you might reconsider this point given the additional context I've provided.

**Comment by rpaul-stripe** [comment] 2024-01-09 21:56
> At a minimum, the error handling should be better, to identify and report the syntax error.

It is reported during validation when the schema is provided. Is there something else we could be doing to report it more effectively?

> it makes sense to me that you would want the parser to be as forgiving as HTML

For our purposes at Stripe, we really favor things being more explicit and less ambiguous. There are also cases where a user may want a single tag to be usable as either self-closing or not depending on context, and having explicit syntax enables that.

We have noticed, however, that there are cases where people forget the forward slash. I'm open to reconsidering the syntax and coming up with a cleaner way of expressing a self-closing tag. I think we still ultimately want it to be explicit so that the schema doesn't have to be present during parsing, though.

For your case, you could probably implement a pre-transform pass that programmatically mutates the AST so that self-closing tags that were written as opening tags still work as expected.

**Comment by mDuo13** [comment] 2024-01-09 22:03
> > At a minimum, the error handling should be better, to identify and report the syntax error.
> 
> It is reported during validation when the schema is provided. Is there something else we could be doing to report it more effectively?

For starters, the sandbox could show some kind of error.

> For our purposes at Stripe, we really favor things being more explicit and less ambiguous... I think we still ultimately want it to be explicit so that the schema doesn't have to be present during parsing, though.

Well, even without the schema, shouldn't an open tag without a corresponding close tag be a syntax error? I'm surprised that the example parses without error.
