### ISSUE TITLE
Hot reloading breaks after one minute with the Next.js starter

### ISSUE THREAD

**Issue by symmb** [markdoc/markdoc#131] opened 2022-07-18 10:50 UTC
### What happened?

Whenever I run `npm run dev` and leave the page untouched in the browser and editor for about a minute, hot reloading doesn't have an effect anymore. The Next.js reload indicator in the lower right corner still shows up but the page does not update when I change something in my sources. Refreshing the page or performing any sort of page navigation (without a full reload) fixes hot reloading until it breaks again after one minute.

### To reproduce

1. Clone the [Next.js starter project](https://github.com/markdoc/markdoc-starter/tree/cf36368f405a41499aded8b61b136c0bda44c0e3) and install dependencies using `npm install`
2. Start `npm run dev`
3. Load the page in a browser
4. Wait for one minute
5. Change something in a page file
6. The Next.js reloading indicator shows up but the page is not updated

### Version

0.1.4

### Additional context

The exact commit of the starter repository used is cf36368f405a41499aded8b61b136c0bda44c0e3.

This problem doesn't occur with a Next.js starter project without Markdoc, so it doesn't seem to be a Next.js issue.

I'm also not seeing any errors or warnings in the browser console or network tab.

**Comment by symmb** [comment] 2022-07-19 16:13
I'm on openSUSE Leap 15.3 and I've tested it on both Google Chrome (Version 103.0.5060.114) and Firefox (91.10.0esr).

**Comment by jensneuse** [comment] 2022-07-21 07:32
same problem for me on macos 12.4 with Chrome Version 103.0.5060.114 (Official Build) (arm64)

**Comment by leerob** [comment] 2022-07-22 22:04
Sorry about this experience – @mfix-stripe let me know if you need any support from the Next.js side.

**Comment by mfix-stripe** [comment] 2022-07-22 22:24
> Sorry about this experience – @mfix-stripe let me know if you need any support from the Next.js side.

Ayy, thanks for offering @leerob! I don't think anything special is going on in our plugin that could cause this to happen, so feels like a Next.js specific bug to me. Especially since our plugin [mimics](https://github.com/markdoc/next.js/blob/main/src/index.js) the MDX plugin almost identically: https://github.com/vercel/next.js/blob/canary/packages/next-mdx/index.js

Cc'ing @ijjk in case something jumps out at him (since he just took a look at our plugin this week).

**Comment by ijjk** [comment] 2022-07-23 14:40
Taking an initial look I'm not able to reproduce the HMR failing after a certain amount of time, it may be related to certain files being edited. To ensure webpack is tracking any files referenced the different loader dependencies can be added for example here's how it is managed in the postcss loader https://github.com/vercel/next.js/blob/8b721227cf82a0af3be07663dc8d218430c80514/packages/next/build/webpack/loaders/postcss-loader/src/index.js#L89-L103

**Comment by mfix-stripe** [comment] 2022-07-25 20:44
Thanks for taking a look @ijjk. We do currently add a context dependency to the entire `markdoc/` dir (https://github.com/markdoc/next.js/blob/09712e2bd2add910e4de38ee19da4a8288ad289d/src/loader.js#L198), and @symmb mentioned the HMR stops working for the `pages/` dir, so I don't think that is the issue. 


I am actually fairly certain this is the problem: https://github.com/vercel/next.js/issues/19230 and https://github.com/vercel/next.js/discussions/12149

We used to force a page refresh on save in `@markdoc/next.js`, but we felt like that was unidiomatic and flakey, plus the same code could be run in user-land. 

@ijjk do you have any suggested work arounds for this?

**Comment by mfix-stripe** [comment] 2022-08-03 20:27
@ijjk any thoughts on the above? Is there a idiomatic way to force `getStaticProps` to re-run on save?

**Comment by ijjk** [comment] 2022-08-03 21:00
Hmm we do have a test for server import changes triggering the data to be refreshed client-side [without reloading here](https://github.com/vercel/next.js/blob/2722876eb580f65439f898db6d1fb03c5c0bc5c5/test/development/basic/gssp-ssr-change-reloading/test/index.test.ts#L314), if we could track down a test case for this we could investigate patching this easier.

**Comment by mfix-stripe** [comment] 2022-08-22 22:50
@ijjk super strange, but I was actually able to reproduce this issue with our starter repo: https://github.com/markdoc/markdoc-starter

If you boot up the repo, HMR/Fast Refresh works great. But if you wait a few minutes and try to make edits, it no longer works. 

Is this enough of a repro for you? I can try to write a test for this, but not sure how I would at the moment

**Comment by ijjk** [comment] 2022-08-22 23:05
Are you able to reproduce this on the bare Next.js starter from `pnpm create next-app` or is this only occurring with `markdoc` configured?

**Comment by mfix-stripe** [comment] 2022-08-22 23:51
@ijjk it happens with the plain Next.js starter too. Here is a repo that reproduces the issue: https://github.com/mfix-stripe/nextjs-hmr-repro

If you wait a minute or 2 and then try and edit the `x` string in `data/server.js`, the page will not HMR. If you refresh the page, HMR starts working again.

**Comment by ijjk** [comment] 2022-08-23 03:42
Ah I see, thanks for narrowing in on that! I was able to track this down to an issue with our entries handling and opened a fix/regression test for this in https://github.com/vercel/next.js/pull/39845

**Comment by ijjk** [comment] 2022-08-23 15:27
Hi, this should now be fixed in `v12.2.6-canary.2` of Next.js, please update and give it a try!

**Comment by mfix-stripe** [comment] 2022-08-23 16:19
Thanks @ijjk! I just tested this with `v12.2.6-canary.2`, and that fixed the problem. Closing 👍

**Closed by mfix-stripe** 2022-08-23 16:19 UTC
Labels: bug, good first issue, help wanted, next.js

**Comment by symmb** [comment] 2022-08-29 13:16
Can confirm it works with the latest Next.js canary + Markdoc. Thanks to everyone involved!
