### ISSUE TITLE
Nextjs markdoc starter failing

### ISSUE THREAD

**Issue by Siumauricio** [markdoc/markdoc#98] opened 2022-06-18 06:29 UTC
### What happened?

The current nextjs starter repo are not working on windows.

I expect to work.

### To reproduce

Download the next repo starter.
Run on machine Windows

### Version

Latest of nextjs and markdoc

### Additional context

This is the error throwing in the browser, I also tested in another project mine

![image](https://user-images.githubusercontent.com/47042324/174425849-c5b41eea-1602-4404-9e8b-971f8744c16f.png)

**Comment by arranf** [comment] 2022-06-18 11:43
I'm seeing something similar when trying to run my Nextjs site on Windows. Same `Module parse: unexpected token` error for `.tsx` files.

I am using the latest libraries (0.14 `@markdoc/nextjs`, 0.13 markdoc).

Same project works fine on Ubuntu.

**Comment by Siumauricio** [comment] 2022-06-18 22:38
Yeah looks like this issue is only in Windows, the only way that I be found is running trough WSL ( Ubuntu 20.04)

**Comment by mfix-stripe** [comment] 2022-06-20 21:00
This is a duplicate of https://github.com/markdoc/markdoc/issues/85—please add information to that issue so we can track it 🙂 

Also @arranf @Siumauricio if you are able to push a fix for this issue, that would be fantastic. I don't have access to a Windows machine at the moment.

**Closed by mfix-stripe** 2022-06-20 21:00 UTC
Labels: bug
