### ISSUE TITLE
nested children in selfclosed html tag in 0.3.0

### ISSUE THREAD

**Issue by u-yas** [markdoc/markdoc#404] opened 2023-06-12 11:24 UTC
### What happened?

In markdoc up to v0.2.2, it was displayed normally with the html tag rendering code in [the following issue comment](https://github.com/markdoc/markdoc/issues/10#issuecomment-1492560830)

https://gist.github.com/rpaul-stripe/941eb22c4779ea87b1adf7715d76ca08

However, since 0.3, when I try to render with the same code, it doesn't display properly.

This is my reproduce repository
https://github.com/u-yas/repro-markdoc-overnesting-selfclose

Now, the display below the `<br />` tag is also rendered normally.
https://github.com/u-yas/repro-markdoc-overnesting-selfclose/blob/main/output-v0.2.2/output.html

But it's not rendering in v0.3.0.
https://github.com/u-yas/repro-markdoc-overnesting-selfclose/blob/main/output-v0.3.0/output.html

I left intermediate generated json for debugging under these folders.
Comparing the transformed.json, you can see that in v0.3.0, the markdown content after that is nested in the Children of the br tag. I'm thinking this is probably the reason why it's not showing up.

https://github.com/u-yas/repro-markdoc-overnesting-selfclose/blob/main/output-v0.3.0/transformed.json

https://github.com/u-yas/repro-markdoc-overnesting-selfclose/blob/main/output-v0.2.2/transformed.json

I couldn't determine if the cause of these bugs was simply that the Gist code was not compatible with v0.3, or if the markdoc itself contained a bug, so I raised it as an issue. Thank you for your confirmation.

### To reproduce

1. install @markdoc/markdoc@0.3.0
2. Try entering the following into the example string in the [following gist code](https://gist.github.com/rpaul-stripe/941eb22c4779ea87b1adf7715d76ca08)

```javascript
const example = `
this is example doc
<div>
since v0.3 the content below from here is not shown
</div>
<br />

MarkDoc is

<br />
<br />

great tool!!
`;
```

3. not displayed `MarkDoc is great tool!!` 😢  (but 0.2.2 is displayed)

### Version

0.3.0

### Additional context

I understand that markdoc does not natively support html tags as a feature. However, it was not possible to judge whether this change was the intended behavior. 😢

**Comment by rpaul-stripe** [comment] 2023-06-12 15:14
It looks like this is actually caused by an error in my example. In the `onclosetag` function, the line that says `meta: {tag: "html_close"}` should actually be `meta: {tag: "html-tag"}`. This error is causing it to render incorrectly in 0.3.0 because the 0.3.0 release [fixes a bug](https://github.com/markdoc/markdoc/pull/376) that caused the parser to ignore when opening and closing tag names don't match. 

If you modify the `onclosetag` function accordingly, it should work with 0.3.0. I've [updated the example](https://gist.github.com/rpaul-stripe/941eb22c4779ea87b1adf7715d76ca08/revisions#diff-2a0b6b61560391b5efd8455a060181d161ae3d33035b53a2d39ed15c1fa266e1) in the gist.

**Closed by rpaul-stripe** 2023-06-12 15:14 UTC
Labels: bug

**Comment by u-yas** [comment] 2023-06-12 16:08
@rpaul-stripe 

I'm really glad it's not a bug in Markdoc itself :heart:   Thank you for your research and gist code fix!  !
